# Generated by Django 3.2.9 on 2021-11-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='curtidas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='curtidas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
