# Generated by Django 3.2.9 on 2021-11-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20211130_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='texto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
